# **Dependancies**

In [181]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras import *
from keras.callbacks import *
import os
from sklearn.preprocessing import MinMaxScaler, RobustScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from commons import mean_absolute_percentage_error
from keras.layers import *
from sklearn.pipeline import Pipeline
import tensorflow as tf
from tensorflow.keras.losses import LogCosh

# **Loading Data**

In [182]:
PATH_TO_DATA = "E:/DS440proj/BTCpred/btc_data-research_paper/reg_interval1.csv"
data = pd.read_csv(PATH_TO_DATA)

In [183]:
data.head()

difficulty3var  fee_to_rewardUSD  hashrate90std  \
0   -4.294967e+09            24.447   5.438008e+18   
1   -5.368709e+09            23.309   5.589062e+18   
2   -5.368709e+09            19.255   5.634595e+18   
3   -5.368709e+09            13.105   6.187523e+18   
4   -5.368709e+09            11.452   6.338603e+18   

   mediantransactionvalue90trxUSD  mining_profitability30trx  price14wmaUSD  \
0                           1.707                      0.516          13714   
1                           1.716                      0.446          13332   
2                           1.722                      0.376          12982   
3                           1.715                      0.162          12322   
4                           1.705                      0.090          12038   

   price30emaUSD  price3wmaUSD  price7smaUSD  price7wmaUSD  price90momUSD  \
0          14124         11780         13261         12798         5091.0   
1          13959         11405         12933         12373         5773.0   
2          13804         11425         12605         12030         5483.0   
3          13456         11694         11695         11707         5555.0   
4          13285         11136         11487         11484         5254.0   

   top100cap90sma  transactionvalue30smaUSD  transactionvalue90emaUSD  \
0          16.875                     96961                     85113   
1          16.886                     96445                     85012   
2          16.897                     96146                     85180   
3          16.941                     94913                     84139   
4          16.958                     94620                     83633   

   priceUSD  
0     10747  
1     11561  
2     11560  
3     11217  
4     10800

In [184]:
data.shape

(866, 15)

In [185]:
y = data['priceUSD'].shift(-1,fill_value=1)

In [186]:
y.head()

0    11561
1    11560
2    11217
3    10800
4    11094
Name: priceUSD, dtype: int64

In [187]:
def create_dataset(dataset, time_step=1):
    dataX = []
    datay = []
    for i in range(len(dataset) - time_step):
        a = dataset.iloc[i:(i + time_step), :].values  # Use .iloc for DataFrame
        dataX.append(a)
        datay.append(dataset.iloc[i + time_step, -1])
    return np.array(dataX), np.array(datay)


In [188]:
 X_train, X_test, y_train, y_test =train_test_split(data,y, test_size=0.2, train_size=0.8, shuffle=False, random_state=8)

In [189]:
X_train.shape

(692, 15)

In [190]:
estimators=[]

In [191]:
estimators.append(['robust',RobustScaler()])

In [192]:
estimators.append(['mixmax',MinMaxScaler()])

In [193]:
scale=Pipeline(estimators,verbose=True)

In [194]:
X_train=scale.fit_transform(X_train)

[Pipeline] ............ (step 1 of 2) Processing robust, total=   0.0s
[Pipeline] ............ (step 2 of 2) Processing mixmax, total=   0.0s


In [195]:
X_test=scale.transform(X_test)

In [196]:
X_train=np.reshape(X_train,(X_train.shape[0],1,X_train.shape[1]))

In [197]:
X_test=np.reshape(X_test,(X_test.shape[0],1,X_test.shape[1]))

In [198]:
y_train=y_train.values

In [199]:
y_train=np.reshape(y_train, (y_train.shape[0],1,1))

In [200]:
y_test=y_test.values

In [201]:
y_test=np.reshape(y_test,(y_test.shape[0],1,1))

In [202]:
X_train.shape

(692, 1, 15)

In [203]:
X_train

array([[[3.31408817e-14, 1.00000000e+00, 0.00000000e+00, ...,
         1.00000000e+00, 9.93024796e-01, 8.66966742e-01]],

       [[3.23876798e-14, 9.52563568e-01, 8.61345104e-03, ...,
         9.93785828e-01, 9.91538518e-01, 9.68742186e-01]],

       [[3.23876798e-14, 7.83576490e-01, 1.12098892e-02, ...,
         9.90184980e-01, 9.94010742e-01, 9.68617154e-01]],

       ...,

       [[2.53075824e-13, 2.60108378e-02, 7.38479840e-01, ...,
         9.72951491e-02, 1.00183945e-01, 4.04351088e-01]],

       [[1.28981646e-01, 3.26385994e-02, 7.43398522e-01, ...,
         9.49828990e-02, 9.80501803e-02, 3.81345336e-01]],

       [[1.93684164e-01, 4.46019175e-02, 7.46143017e-01, ...,
         9.38508599e-02, 9.72113899e-02, 3.96724181e-01]]])

In [204]:
y_train.shape

(692, 1, 1)

In [205]:
y_train

array([[[11561]],

       [[11560]],

       [[11217]],

       [[10800]],

       [[11094]],

       [[11384]],

       [[11085]],

       [[11294]],

       [[11710]],

       [[11372]],

       [[10781]],

       [[10154]],

       [[ 9755]],

       [[ 8748]],

       [[ 9091]],

       [[ 8826]],

       [[ 7704]],

       [[ 6852]],

       [[ 7933]],

       [[ 8256]],

       [[ 8300]],

       [[ 8691]],

       [[ 8234]],

       [[ 8662]],

       [[ 8657]],

       [[ 9055]],

       [[ 9838]],

       [[10058]],

       [[10713]],

       [[10772]],

       [[10902]],

       [[11551]],

       [[10851]],

       [[10325]],

       [[10046]],

       [[ 9975]],

       [[ 9649]],

       [[ 9939]],

       [[10575]],

       [[10607]],

       [[10666]],

       [[11002]],

       [[11365]],

       [[11271]],

       [[11537]],

       [[11051]],

       [[10428]],

       [[ 9724]],

       [[ 8927]],

       [[ 9252]],

       [[ 9065]],

       [[ 9457]],

       [[ 91

# **Model Architecture + Training**

In [206]:
def lr_schedule(epoch):
    """Learning Rate Schedule

    Learning rate is scheduled to be reduced after 80, 120, 160, 180 epochs.
    Called automatically every epoch as part of callbacks during training.

    # Arguments
        epoch (int): The number of epochs

    # Returns
        lr (float32): learning rate
    """
    lr = 1e-3
    if epoch > 180:
        lr *= 0.5e-3
    elif epoch > 160:
        lr *= 1e-3
    elif epoch > 120:
        lr *= 1e-2
    elif epoch > 80:
        lr *= 1e-1
    print('Learning rate: ', lr)
    return lr

In [207]:

adam = optimizers.Adam(learning_rate=lr_schedule(0), amsgrad=True)

Learning rate:  0.001


In [208]:
model = Sequential()
model.add(Bidirectional(LSTM(350, return_sequences=True, activation='relu'), input_shape=(1, X_train.shape[2])))
model.add(Bidirectional(LSTM(350, return_sequences=True, activation='relu')))
model.add(Dense(1))
model.compile(loss="log_cosh", optimizer=adam, metrics=['mae'])

E:\DS440proj\BTCpred\.venv\lib\site-packages\keras\src\layers\core\wrapper.py:27: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [209]:
mcp_save = ModelCheckpoint('model/LSTM_reg_seven_new.keras', save_best_only=True, monitor='val_loss', mode='auto')
earlyStopping = EarlyStopping(monitor='val_loss', patience=100, verbose=1, mode='auto')

In [210]:
#model.compile(optimizer='adam', loss='log_cosh', metrics=['accuracy'])
model.fit(X_train,y_train, epochs=5000, batch_size=32, validation_data=(X_test,y_test), callbacks=[mcp_save,earlyStopping])

Epoch 1/5000
22/22 ━━━━━━━━━━━━━━━━━━━━ 6s 71ms/step - loss: 7868.9038 - mae: 7869.5967 - val_loss: 10004.7998 - val_mae: 10005.4932
Epoch 2/5000
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - loss: 7891.9722 - mae: 7892.6660 - val_loss: 9890.3057 - val_mae: 9890.9990
Epoch 3/5000
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 7823.0229 - mae: 7823.7163 - val_loss: 9385.9482 - val_mae: 9386.6406
Epoch 4/5000
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 7244.4033 - mae: 7245.0962 - val_loss: 7874.8906 - val_mae: 7875.5840
Epoch 5/5000
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 5890.9868 - mae: 5891.6802 - val_loss: 4314.7124 - val_mae: 4315.4058
Epoch 6/5000
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 3015.6438 - mae: 3016.3372 - val_loss: 1946.1733 - val_mae: 1946.8663
Epoch 7/5000
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 1213.9712 - mae: 1214.6643 - val_loss: 1485.0715 - val_mae: 1485.7648
Epoch 8/5000
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1094.6063 - mae: 109

# **Testing Model**

In [211]:
#from tensorflow.keras.models import load_model
#prediction_model = load_model('model/LSTM_reg_seven_new.keras',compile=False)

In [212]:
y_pred = np.ravel(model.predict(X_test))

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


In [213]:
y_test=np.ravel(y_test)

In [214]:
y_pred

array([ 7252.6304,  7514.9824,  7564.5757,  7608.727 ,  7711.8076,
        7729.9536,  8161.7505,  8812.908 ,  8768.04  ,  8867.056 ,
        8974.49  ,  8780.8955,  8869.326 ,  9050.582 ,  9372.69  ,
        9835.937 ,  9681.195 ,  8713.654 ,  8624.28  ,  8607.952 ,
        8856.57  ,  9321.081 ,  9370.993 ,  9317.287 ,  9500.489 ,
        9583.632 ,  9526.408 ,  9552.997 ,  9202.487 ,  9001.067 ,
        9078.959 ,  9033.559 ,  8747.93  ,  8791.634 ,  8959.368 ,
        9243.759 ,  9401.05  ,  9486.851 ,  9535.141 ,  9539.026 ,
        9822.957 ,  9526.416 ,  9684.634 ,  9784.924 ,  9670.047 ,
        9633.303 ,  9701.977 ,  9701.001 ,  9790.78  ,  9693.945 ,
        9468.099 ,  9470.87  ,  9457.8125,  9292.4375,  9521.058 ,
        9613.4795,  9538.239 ,  9370.13  ,  9351.822 ,  9392.017 ,
        9489.679 ,  9647.718 ,  9488.028 ,  9286.436 ,  9242.338 ,
        9167.907 ,  9113.467 ,  9160.525 ,  9197.751 ,  9229.115 ,
        9214.929 ,  9143.173 ,  9159.7705,  9131.425 ,  9245.4

In [215]:
r2=r2_score(y_test,y_pred) #testing score/ r^2
r2

0.5141881600594139

In [216]:
mae=mean_absolute_error(y_test,y_pred) #mae
mae

246.1420309132543

In [217]:
rmse=np.sqrt(mean_squared_error(y_test,y_pred)) #rmse
rmse

894.8456113136394

In [218]:
mape=mean_absolute_percentage_error(y_test,y_pred) #mape
mape

6540.296897257733

In [219]:
pd.DataFrame(zip(['MAE','RMSE','MAPE','R^2'],[mae,rmse,mape,r2])).transpose()

0           1            2         3
0         MAE        RMSE         MAPE       R^2
1  246.142031  894.845611  6540.296897  0.514188

In [220]:
pd.DataFrame([y_test,y_pred]).transpose()

0             1
0     7519.0   7252.630371
1     7541.0   7514.982422
2     7583.0   7564.575684
3     7705.0   7608.727051
4     7726.0   7711.807617
..       ...           ...
169  11370.0  11244.414062
170  11348.0  11180.631836
171  11433.0  11143.896484
172  11582.0  11248.325195
173      1.0  11378.023438

[174 rows x 2 columns]